// <auto-generated />
using System;
using EntityFramework_02.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework_02.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    partial class SchoolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFramework_02.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"), 10L, 10);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasAnnotation("StringLength", (200, 300));

                    b.Property<double>("Duration")
                        .HasColumnType("float")
                        .HasAnnotation("Range", (2, 16));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasAnnotation("StringLength", (50, 20));

                    b.HasKey("CourseId");

                    b.ToTable("Course", "dbo");
                });

            modelBuilder.Entity("EntityFramework_02.Entities.Course_Inst", b =>
                {
                    b.Property<string>("Evaluate")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.ToTable("Course_Inst", "dbo");
                });

            modelBuilder.Entity("EntityFramework_02.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"), 10L, 10);

                    b.Property<DateTime>("HiringDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasComputedColumnSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasAnnotation("StringLength", (50, 20));

                    b.HasKey("DepartmentId");

                    b.ToTable("Department", "dbo");
                });

            modelBuilder.Entity("EntityFramework_02.Entities.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"), 10L, 10);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasAnnotation("StringLength", (40, 10));

                    b.Property<double>("Bouns")
                        .HasColumnType("float");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<double>("HourRate")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasAnnotation("StringLength", (50, 20));

                    b.Property<decimal>("Salary")
                        .HasColumnType("Money")
                        .HasAnnotation("Range", (2000, 10000));

                    b.HasKey("InstructorId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructor", "dbo");
                });

            modelBuilder.Entity("EntityFramework_02.Entities.Stud_Course", b =>
                {
                    b.Property<double>("Grade")
                        .HasColumnType("float")
                        .HasAnnotation("Range", (0, 100));

                    b.ToTable("Stud_Course", "dbo");
                });

            modelBuilder.Entity("EntityFramework_02.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 10L, 10);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasAnnotation("Range", (21, 90));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasAnnotation("StringLength", (50, 20));

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasAnnotation("StringLength", (50, 20));

                    b.HasKey("StudentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Student", "dbo");
                });

            modelBuilder.Entity("EntityFramework_02.Entities.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 10L, 10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar")
                        .HasAnnotation("StringLength", (50, 20));

                    b.HasKey("Id");

                    b.ToTable("Topic", "dbo");
                });

            modelBuilder.Entity("EntityFramework_02.Entities.Instructor", b =>
                {
                    b.HasOne("EntityFramework_02.Entities.Department", "Department")
                        .WithMany("Instructor")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EntityFramework_02.Entities.Student", b =>
                {
                    b.HasOne("EntityFramework_02.Entities.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EntityFramework_02.Entities.Department", b =>
                {
                    b.Navigation("Instructor");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
